version: 2
jobs:
  build:
    working_directory: ~/timekit-io/booking-js
    docker:
    - image: circleci/node@sha256:9d36d9f21a4448b448553e6fb15ed322a599c57d8bd3c3fb16b6e65eb38b8735
    steps:
    - checkout
    - git config --global url."https://".insteadOf git://
    # Restore the dependency cache
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-{{ .Revision }}
        # Default branch if not
        - v1-dep-master-
    - run:
        name: Install dependencies
        command: |
            node -v
            yarn -v
            yarn install --pure-lockfile
            yarn add sass
    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ .Revision }}
        paths:
        - ~/.cache/yarn
        - ./node_modules
    # Run frontend tests
    - run:
        name: Test unit suite and build prod
        command: |
            yarn run test